- name: Deploy mysql database
  hosts: localhost
  vars_files:
    - ../vars.yml
  tasks:
    - name: Check if mysql namespace exists
      shell: kubectl get namespace mysql --ignore-not-found
      register: namespace_check
      changed_when: false

    - name: End playbook if mysql namespace exists
      meta: end_play
      when: namespace_check.stdout != ""

    - name: Add bitnami Helm repository
      command: helm repo add bitnami https://charts.bitnami.com/bitnami
      environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ http_proxy }}"
        no_proxy: "{{ no_proxy }}"

    - name: Update Helm repositories
      command: helm repo update
      environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ http_proxy }}"
        no_proxy: "{{ no_proxy }}"

    - name: Create 'mysql' namespace
      command: kubectl create ns mysql

    - name: Install MySQL using Helm
      command: helm install mysql bitnami/mysql -n mysql -f ../helm-values/mysqldb.yaml
      environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ http_proxy }}"
        no_proxy: "{{ no_proxy }}"

    - name: Wait for mysql-0 pod to be ready
      command: kubectl wait --for=condition=ready pod -l app.kubernetes.io/instance=mysql -n mysql --timeout=300s