- name: Deploy prometheus and grafana with local-path-storage
  hosts: localhost
  vars_files:
    - ../vars.yml
  tasks:
    - name: Check if monitoring namespace exists
      shell: kubectl get namespace monitoring --ignore-not-found
      register: monitoring_namespace_check
      changed_when: false
    
    - name: Create monitoring namespace
      command: kubectl create namespace monitoring
      when: monitoring_namespace_check.stdout == ""
    
    - name: Add Prometheus Helm repository
      command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ http_proxy }}"
        no_proxy: "{{ no_proxy }}"
    
    - name: Update Helm repositories
      command: helm repo update
      environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ http_proxy }}"
        no_proxy: "{{ no_proxy }}"
    
    # Installing the CRDs needed
    - name: Helm install kube-prometheus-stack
      command: helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack -n monitoring
      ignore_errors: yes
      environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ http_proxy }}"
        no_proxy: "{{ no_proxy }}"
    
    - name: Delete kube-prometheus-stack
      command: helm delete kube-prometheus-stack -n monitoring
      ignore_errors: yes
    
    - name: Apply customized kube-prometheus-stack
      command: kubectl apply -f ../manifests/monitoring-manifest.yaml