---
- name: Setup local path storage provisioner
  hosts: localhost
  vars_files:
    - ../vars.yml
  tasks:
    - name: Check if local-path-storage namespace exists
      shell: kubectl get namespace local-path-storage --ignore-not-found
      register: namespace_check
      ignore_errors: yes
      changed_when: false
    
    - name: Install local-path-provisioner if namespace does not exist
      shell: kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.30/deploy/local-path-storage.yaml
      environment:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ http_proxy }}"
        no_proxy: "{{ no_proxy }}"
      when: namespace_check.stdout == ""
      register: apply_output
    
    - name: Wait for local-path-provisioner to be ready
      shell: kubectl wait --for=condition=Ready pod -l app=local-path-provisioner -n local-path-storage --timeout=120s
      when: namespace_check.stdout == ""
